insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Mpower TV S239', 1);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 300', 2);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E1160', 3);
insert into cart (cartItemId, productId, quantity) values ('Sendo', 'Sendo SV663', 4);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Note 10.1 (2014)', 5);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer beTouch E120', 6);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Andy 5E5', 7);
insert into cart (cartItemId, productId, quantity) values ('i-mate', 'i-mate SP3', 8);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Xperia Arc S', 9);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-810D', 10);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GW550', 11);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Z61', 12);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N908', 13);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Juice 4G Q461', 14);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax A77 Canvas Juice', 15);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola V290', 16);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-983', 17);
insert into cart (cartItemId, productId, quantity) values ('Infinix', 'Infinix Hot 5', 18);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-C555', 19);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-S120', 20);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus Black (White version)', 21);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Mi 4i', 22);
insert into cart (cartItemId, productId, quantity) values ('Sewon', 'Sewon SG-2300CD', 23);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor Play4 Pro', 24);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo S560', 25);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice Fire One (Mi-FX-1)', 26);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M610', 27);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia E4g', 28);
insert into cart (cartItemId, productId, quantity) values ('Sendo', 'Sendo S600', 29);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola C230', 30);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Lumia 730 Dual SIM', 31);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A Plus', 32);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn S1 Titanium', 33);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Pioneer P2S', 34);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Amaze 4G', 35);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenwatch 2 WI502Q', 36);
insert into cart (cartItemId, productId, quantity) values ('Google', 'Google Pixel', 37);
insert into cart (cartItemId, productId, quantity) values ('Sendo', 'Sendo S230', 38);
insert into cart (cartItemId, productId, quantity) values ('T-Mobile', 'T-Mobile Comet', 39);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer neoTouch P300', 40);
insert into cart (cartItemId, productId, quantity) values ('T-Mobile', 'T-Mobile Sidekick Slide', 41);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Armani', 42);
insert into cart (cartItemId, productId, quantity) values ('Coolpad', 'Coolpad Note 3 Lite', 43);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Bolt S301', 44);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Round G910S', 45);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia C3-01 Gold Edition', 46);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung X100', 47);
insert into cart (cartItemId, productId, quantity) values ('Sendo', 'Sendo X', 48);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo R5', 49);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-380', 50);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Lumia 625', 51);
insert into cart (cartItemId, productId, quantity) values ('HP', 'HP iPAQ h6310', 52);
insert into cart (cartItemId, productId, quantity) values ('Prestigio', 'Prestigio MultiPhone 5451 Duo', 53);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo LePad S2010', 54);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo NEX 3S 5G', 55);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic Eluga L 4G', 56);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC 804N', 57);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 516 dual sim', 58);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Tag 3G', 59);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab 3 Lite 7.0 3G', 60);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson W610', 61);
insert into cart (cartItemId, productId, quantity) values ('Energizer', 'Energizer Energy 400 LTE', 62);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Q800', 63);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy M40', 64);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO X1000', 65);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel 2012', 66);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus L3 E400', 67);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Kis 3', 68);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KT610', 69);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GS107', 70);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Liquid X2', 71);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU R1 Plus', 72);
insert into cart (cartItemId, productId, quantity) values ('Energizer', 'Energizer Energy E241s', 73);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N109', 74);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem my230x', 75);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C337', 76);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy M20', 77);
insert into cart (cartItemId, productId, quantity) values ('Apple', 'Apple iPad Pro 11 (2018)', 78);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KF245', 79);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG P520', 80);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips X710', 81);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon Q5K Power', 82);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC One SC', 83);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Imperial', 84);
insert into cart (cartItemId, productId, quantity) values ('Kyocera', 'Kyocera Presto S1350', 85);
insert into cart (cartItemId, productId, quantity) values ('Dell', 'Dell Venue Pro', 86);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens C65', 87);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola VE66', 88);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 106', 89);
insert into cart (cartItemId, productId, quantity) values ('Sharp', 'Sharp GX22', 90);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz 4.5EL LTE', 91);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Samba', 92);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 1662', 93);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Phantom 6', 94);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor MagicWatch 2', 95);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei U7310', 96);
insert into cart (cartItemId, productId, quantity) values ('Sonim', 'Sonim XP3 Enduro', 97);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C3333', 98);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Pova', 99);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A6000', 100);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Idol 4', 101);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson G705', 102);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava P7', 103);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia Z3', 104);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Nexus 5', 105);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung U100', 106);
insert into cart (cartItemId, productId, quantity) values ('Casio', 'Casio G''zOne Ravine', 107);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia N-Gage QD', 108);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A5860', 109);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Z3 Corporate', 110);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Camon 16 Premier', 111);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Hazel', 112);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview X2 Soul Style', 113);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Iris 405+', 114);
insert into cart (cartItemId, productId, quantity) values ('Sewon', 'Sewon SG-2000CS', 115);
insert into cart (cartItemId, productId, quantity) values ('Bird', 'Bird V5510', 116);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson W715', 117);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus Elite LS696', 118);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Poco X3 NFC', 119);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei P smart 2021', 120);
insert into cart (cartItemId, productId, quantity) values ('Benefon', 'Benefon iO', 121);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung B7320 OmniaPRO', 122);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab J', 123);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Moto G Dual SIM (2nd gen)', 124);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C77', 125);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-S107', 126);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-213', 127);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Prime 5.0', 128);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y53', 129);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee M6', 130);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Flipper 2', 131);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola T725', 132);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GW910', 133);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G Flex2', 134);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Y5 lite (2018)', 135);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon Q450', 136);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei U8220', 137);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier V190', 138);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola RAZR V XT889', 139);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile B800', 140);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Q61', 141);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Raider 4G', 142);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee A1 Lite', 143);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung R220', 144);
insert into cart (cartItemId, productId, quantity) values ('BlackBerry', 'BlackBerry KEY2', 145);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia SL', 146);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung i7410', 147);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung i300', 148);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Iris X5', 149);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem MY C-4', 150);
insert into cart (cartItemId, productId, quantity) values ('Bird', 'Bird S663', 151);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn Sparkle V', 152);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A22', 153);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo V19', 154);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Photon 4G MB855', 155);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung I9000 Galaxy S', 156);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier V730', 157);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy C5', 158);
insert into cart (cartItemId, productId, quantity) values ('Coolpad', 'Coolpad Legacy 5G', 159);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Caliber II', 160);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE U880E', 161);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo U3', 162);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia 10 III', 163);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung SGH-600', 164);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus PadFone Infinity Lite', 165);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor 7i', 166);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Panther', 167);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus PadFone Infinity Lite', 168);
insert into cart (cartItemId, productId, quantity) values ('Sonim', 'Sonim XP1300 Core', 169);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KG195', 170);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Redmi 10X 4G', 171);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Ascend P6 S', 172);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G5400', 173);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier M320+', 174);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone 231', 175);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Pop 2 F', 176);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic X88', 177);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO A600', 178);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N100', 179);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy A50s', 180);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens ME45', 181);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6.1', 182);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia XA Ultra', 183);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Genius', 184);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei G8', 185);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M930 Transform Ultra', 186);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG K40', 187);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG K8 (2017)', 188);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax X215', 189);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y91i (India)', 190);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Bello II', 191);
insert into cart (cartItemId, productId, quantity) values ('BlackBerry', 'BlackBerry Torch 9810', 192);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice G-6565', 193);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Grand M2 LTE', 194);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Studio J8', 195);
insert into cart (cartItemId, productId, quantity) values ('Sonim', 'Sonim XP7', 196);
insert into cart (cartItemId, productId, quantity) values ('Amazon', 'Amazon Fire 7 (2017)', 197);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KM555E', 198);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 225 4G', 199);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A820', 200);
insert into cart (cartItemId, productId, quantity) values ('Prestigio', 'Prestigio MultiPad 7.0 Ultra +', 201);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo Tab V7', 202);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier Z300', 203);
insert into cart (cartItemId, productId, quantity) values ('Toshiba', 'Toshiba G710', 204);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Stylus 2 Plus', 205);
insert into cart (cartItemId, productId, quantity) values ('Sewon', 'Sewon SG-2000', 206);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic A210', 207);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KP265', 208);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy A20', 209);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Tank', 210);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Poco M3', 211);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola A910', 212);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo IdeaTab A1000', 213);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Vdeo 3', 214);
insert into cart (cartItemId, productId, quantity) values ('Innostream', 'Innostream INNO 30', 215);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG CT810 Incite', 216);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia ion HSPA', 217);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia C', 218);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel One Touch S''Pop', 219);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem MC 825 FM', 220);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C777', 221);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson J210', 222);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Fire 6 Q428', 223);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Ten 3G', 224);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo C2', 225);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia R1 (Plus)', 226);
insert into cart (cartItemId, productId, quantity) values ('Telit', 'Telit C1000', 227);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Spark', 228);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Mate S', 229);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo X6S Plus', 230);
insert into cart (cartItemId, productId, quantity) values ('Pantech', 'Pantech Ease', 231);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice M-67 3D', 232);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Flash 2', 233);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus L1 II Tri E475', 234);
insert into cart (cartItemId, productId, quantity) values ('Sewon', 'Sewon SG-2890CD', 235);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor Magic', 236);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E370', 237);
insert into cart (cartItemId, productId, quantity) values ('Coolpad', 'Coolpad 3632', 238);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Q500', 239);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem my215x', 240);
insert into cart (cartItemId, productId, quantity) values ('Bird', 'Bird S798', 241);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C6620', 242);
insert into cart (cartItemId, productId, quantity) values ('BenQ', 'BenQ A500', 243);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor Watch ES', 244);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Z558', 245);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO LT900', 246);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Redmi Note', 247);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Z5x (2020)', 248);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Asha 201', 249);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus 2 AS680', 250);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia E66', 251);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Deejay II', 252);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Blade 10 Prime', 253);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenfone 6 A601CG (2014)', 254);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung S5560 Marvel', 255);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson K770', 256);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung F300', 257);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola RAZR maxx V6', 258);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Era 2', 259);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung L600', 260);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung i600', 261);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee M30', 262);
insert into cart (cartItemId, productId, quantity) values ('Archos', 'Archos 45 Titanium', 263);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG C105', 264);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei P20 lite (2019)', 265);
insert into cart (cartItemId, productId, quantity) values ('BQ', 'BQ  Aquaris M10', 266);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson K700', 267);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Iris Win1', 268);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Pop C7', 269);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo Reno 10x zoom', 270);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 526G+ dual sim ', 271);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG U8120', 272);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG A190', 273);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic P11', 274);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei P9 lite mini', 275);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 9110i Communicator', 276);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips D633', 277);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei nova plus', 278);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N600', 279);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Charm', 280);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax A52', 281);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Incredible S', 282);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung J800 Luxe', 283);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KF757 Secret', 284);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Idol 3 (5.5)', 285);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Pop Astro', 286);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG T315', 287);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Tab P650', 288);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia N86 8MP', 289);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-997D', 290);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG V50S ThinQ 5G', 291);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia 5 Plus', 292);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Axon 11 SE 5G', 293);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax X225', 294);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Armani', 295);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia X 5G', 296);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab Pro 8.4', 297);
insert into cart (cartItemId, productId, quantity) values ('T-Mobile', 'T-Mobile myTouch 4G', 298);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Xenium X806', 299);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KU970 Shine', 300);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Wave M S7250', 301);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E750', 302);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus Black P970', 303);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Liquid Z410', 304);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel One Touch Scribe X', 305);
insert into cart (cartItemId, productId, quantity) values ('Sharp', 'Sharp Aquos D10', 306);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E500', 307);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Asha 311', 308);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Redmi Note 9 Pro 5G', 309);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool R80L Granite II', 310);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips X630', 311);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU C5 LTE', 312);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Fire', 313);
insert into cart (cartItemId, productId, quantity) values ('Coolpad', 'Coolpad Max', 314);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C55', 315);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson G700', 316);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens M65', 317);
insert into cart (cartItemId, productId, quantity) values ('T-Mobile', 'T-Mobile MDA Compact V', 318);
insert into cart (cartItemId, productId, quantity) values ('Prestigio', 'Prestigio MultiPad 8.0 Pro Duo', 319);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor 9S', 320);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola DROID RAZR XT912', 321);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 3108', 322);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG X350', 323);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung J800 Luxe', 324);
insert into cart (cartItemId, productId, quantity) values ('Wiko', 'Wiko Lenny2', 325);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Z801', 326);
insert into cart (cartItemId, productId, quantity) values ('Meizu', 'Meizu C9 Pro', 327);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Q105', 328);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem MY G5', 329);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Rush M830', 330);
insert into cart (cartItemId, productId, quantity) values ('Coolpad', 'Coolpad Cool 10', 331);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Memo', 332);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon CT-888', 333);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Pop i559', 334);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone 228', 335);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KU800', 336);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung D488', 337);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips 636', 338);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola C117', 339);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy C7', 340);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo Yoga Tablet 10', 341);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn A10', 342);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M920 Transform', 343);
insert into cart (cartItemId, productId, quantity) values ('Qtek', 'Qtek S100', 344);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 9300', 345);
insert into cart (cartItemId, productId, quantity) values ('O2', 'O2 Ice', 346);
insert into cart (cartItemId, productId, quantity) values ('Sharp', 'Sharp Aquos Crystal 2', 347);
insert into cart (cartItemId, productId, quantity) values ('Coolpad', 'Coolpad Note 5', 348);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo K12 Pro', 349);
insert into cart (cartItemId, productId, quantity) values ('BenQ', 'BenQ P50', 350);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone 248', 351);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Pioneer P6', 352);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Bello II', 353);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C3060R', 354);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6600i slide', 355);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Ascend Y200', 356);
insert into cart (cartItemId, productId, quantity) values ('Yota', 'Yota YotaPhone 3', 357);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus Q LU2300', 358);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE V9+', 359);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool i122', 360);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia M5 Dual', 361);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Rainbow', 362);
insert into cart (cartItemId, productId, quantity) values ('Pantech', 'Pantech Impact', 363);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung S5233T', 364);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview P6 Stony', 365);
insert into cart (cartItemId, productId, quantity) values ('HP', 'HP iPAQ hw6915', 366);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GC900 Viewty Smart', 367);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax A87 Ninja 4.0', 368);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia C2-00', 369);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile Noir LT700 Pro', 370);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E1170', 371);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A91', 372);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A53', 373);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Mi 1S', 374);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC ThunderBolt 4G', 375);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung R220', 376);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo S660', 377);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO A500', 378);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus ROG Phone 3 Strix', 379);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 620G dual sim', 380);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A220', 381);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier V1000', 382);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem my401X', 383);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Redmi Note 7S', 384);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Xplay7', 385);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson W580', 386);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview P6 Pro', 387);
insert into cart (cartItemId, productId, quantity) values ('BenQ-Siemens', 'BenQ-Siemens C32', 388);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Debut', 389);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-V270', 390);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG U8110', 391);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy S20', 392);
insert into cart (cartItemId, productId, quantity) values ('Energizer', 'Energizer Ultimate U620S Pop', 393);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice Stellar 507 (Mi-507)', 394);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Bolt Supreme Q300', 395);
insert into cart (cartItemId, productId, quantity) values ('Bird', 'Bird S699', 396);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Liquid S2', 397);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens A65', 398);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Andy 6Q', 399);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy S II T989', 400);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei U8220', 401);
insert into cart (cartItemId, productId, quantity) values ('Telit', 'Telit T510', 402);
insert into cart (cartItemId, productId, quantity) values ('Eten', 'Eten glofiish X600', 403);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee A1 Plus', 404);
insert into cart (cartItemId, productId, quantity) values ('HP', 'HP iPAQ hw6910', 405);
insert into cart (cartItemId, productId, quantity) values ('Wiko', 'Wiko Sunny', 406);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy S6 edge+', 407);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Sensation 4G', 408);
insert into cart (cartItemId, productId, quantity) values ('Wiko', 'Wiko Ufeel', 409);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GX200', 410);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola W220', 411);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GB210', 412);
insert into cart (cartItemId, productId, quantity) values ('Infinix', 'Infinix Hot 4 Pro', 413);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG F2410', 414);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview Viva Home', 415);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Fold 5G', 416);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Shine', 417);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Prime 5.0 Plus', 418);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy A5 (2016)', 419);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT 715', 420);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview X3 Soul Style', 421);
insert into cart (cartItemId, productId, quantity) values ('Archos', 'Archos 53 Titanium', 422);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Dream', 423);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Bolt Q381', 424);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Iris 348', 425);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo V5 Lite (vivo 1609)', 426);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GM360 Viewty Snap', 427);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-800 One Touch Tribe', 428);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GB106', 429);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Epic T', 430);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6125', 431);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas xp 4G Q413', 432);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung I8200 Galaxy S III mini VE', 433);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo Tab S8', 434);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Fold', 435);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo R1S', 436);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N820', 437);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Orbit', 438);
insert into cart (cartItemId, productId, quantity) values ('Gigabyte', 'Gigabyte GSmart MS802', 439);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Nova Messenger', 440);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor Play 8A', 441);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Poco X2', 442);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y11s', 443);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview X2 Soul Style', 444);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C207', 445);
insert into cart (cartItemId, productId, quantity) values ('BenQ-Siemens', 'BenQ-Siemens S88', 446);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Mate 30', 447);
insert into cart (cartItemId, productId, quantity) values ('Mitac', 'Mitac MIO Explora K70', 448);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A706', 449);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Max XL', 450);
insert into cart (cartItemId, productId, quantity) values ('Maxwest', 'Maxwest Orbit 4400', 451);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview Viva i10G', 452);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Z80', 453);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y51 (2015)', 454);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Studio C 5 + 5 LTE', 455);
insert into cart (cartItemId, productId, quantity) values ('Pantech', 'Pantech Crux', 456);
insert into cart (cartItemId, productId, quantity) values ('Ericsson', 'Ericsson GF 388', 457);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia N-Gage', 458);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice N-300', 459);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Elm', 460);
insert into cart (cartItemId, productId, quantity) values ('NIU', 'NIU Tek 5D', 461);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung B3210 CorbyTXT', 462);
insert into cart (cartItemId, productId, quantity) values ('Garmin-Asus', 'Garmin-Asus nuvifone A50', 463);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Z81', 464);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Xcover 4s', 465);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C3560', 466);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia Red Magic', 467);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus L5 E610', 468);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile Noir A750', 469);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 310', 470);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Neo X Mini', 471);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 106 (2018)', 472);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson C702', 473);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo F15', 474);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Brooklyn', 475);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C180', 476);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem my900C', 477);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Asha 503 Dual SIM', 478);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C260', 479);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E1182', 480);
insert into cart (cartItemId, productId, quantity) values ('Archos', 'Archos 50 Cobalt', 481);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn A5', 482);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Q1000s plus', 483);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A57', 484);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice Stellar 507 (Mi-507)', 485);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Sensation 4G', 486);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview Twin X2', 487);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Moto G (2nd gen)', 488);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT View db @', 489);
insert into cart (cartItemId, productId, quantity) values ('Telit', 'Telit t410', 490);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus M', 491);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens SX1', 492);
insert into cart (cartItemId, productId, quantity) values ('Meizu', 'Meizu MX5e', 493);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Z750', 494);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Redmi K20 Pro Premium', 495);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG A100', 496);
insert into cart (cartItemId, productId, quantity) values ('Orange', 'Orange Rio II', 497);
insert into cart (cartItemId, productId, quantity) values ('Gigabyte', 'Gigabyte g-YoYo', 498);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung S3770', 499);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei G8', 500);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung A517', 501);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax X368', 502);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung ZV10', 503);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Touch Book 7.0', 504);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips V726', 505);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone 858 Smart', 506);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C3520', 507);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG L5100', 508);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenpad 8.0 Z380M', 509);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier V1000', 510);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Phantom 6', 511);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G1600', 512);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy J7 Nxt', 513);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Grand S Pro', 514);
insert into cart (cartItemId, productId, quantity) values ('BlackBerry', 'BlackBerry Priv', 515);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava X11', 516);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Advance 4.0 M', 517);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A53 5G', 518);
insert into cart (cartItemId, productId, quantity) values ('Telit', 'Telit X60i', 519);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG A395', 520);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Andy 5EI', 521);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung N620', 522);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola L2', 523);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava Iris 410', 524);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Axe LTE', 525);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Gear', 526);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 515', 527);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Era 4G', 528);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus F3Q', 529);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC DB4100', 530);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola One Zoom', 531);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Q372 Unite 3', 532);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava A68', 533);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo R7 lite', 534);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Gio S5660', 535);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT 835', 536);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Express I8730', 537);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview P5 Qmax', 538);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Premier I9260', 539);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Ascend G615', 540);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn A2+', 541);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C607', 542);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 8600 Luna', 543);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 2710 Navigation Edition', 544);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC P3600i', 545);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KP220', 546);
insert into cart (cartItemId, productId, quantity) values ('Wiko', 'Wiko Tommy2 Plus', 547);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Touch Book 7.0', 548);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips S396', 549);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem WA 3050', 550);
insert into cart (cartItemId, productId, quantity) values ('BenQ-Siemens', 'BenQ-Siemens SL80', 551);
insert into cart (cartItemId, productId, quantity) values ('Sewon', 'Sewon SRD-200', 552);
insert into cart (cartItemId, productId, quantity) values ('Vertu', 'Vertu Ascent 2010', 553);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Tingle', 554);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Rainbow', 555);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C770N', 556);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic Eluga Ray X', 557);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool s5200 Orion', 558);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool s4002 Leo', 559);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E2600', 560);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Stratosphere II I415', 561);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola W180', 562);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola DEFY+', 563);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Lumia Icon', 564);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Liquid Z3', 565);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia Watch', 566);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung I5500 Galaxy 5', 567);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Ascend Y600', 568);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool i130', 569);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C1', 570);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia C2-00', 571);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Q75', 572);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Style Messanger', 573);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Ace Style', 574);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y22', 575);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A39', 576);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips X100', 577);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Q700i', 578);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola GLEAM+ WX308', 579);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT View db @', 580);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 105 (2019)', 581);
insert into cart (cartItemId, productId, quantity) values ('Kyocera', 'Kyocera E3500', 582);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung S6700', 583);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool i601', 584);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo Find X2', 585);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus L9 P769', 586);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia Red Magic 5S', 587);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Grand M', 588);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A42', 589);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M150', 590);
insert into cart (cartItemId, productId, quantity) values ('Realme', 'Realme C1 (2019)', 591);
insert into cart (cartItemId, productId, quantity) values ('Realme', 'Realme Q2i', 592);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G1600', 593);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia Z5S mini NX403A', 594);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Q1010i', 595);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips TM700', 596);
insert into cart (cartItemId, productId, quantity) values ('Apple', 'Apple iPad mini 3', 597);
insert into cart (cartItemId, productId, quantity) values ('Amoi', 'Amoi E76', 598);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT 735', 599);
insert into cart (cartItemId, productId, quantity) values ('Bird', 'Bird S288 Plus', 600);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy C5 Pro', 601);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic P77', 602);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Q105', 603);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO A1010', 604);
insert into cart (cartItemId, productId, quantity) values ('Archos', 'Archos 50 Cobalt', 605);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung A237', 606);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Studio 5.5 HD', 607);
insert into cart (cartItemId, productId, quantity) values ('Microsoft', 'Microsoft Lumia 950 XL Dual SIM', 608);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E1117', 609);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz 4.5EL LTE', 610);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung DoubleTime I857', 611);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Transformer Pad TF300TG', 612);
insert into cart (cartItemId, productId, quantity) values ('Wiko', 'Wiko Wax', 613);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Bar Q', 614);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Ozeo', 615);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Energy X Plus', 616);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC e1108', 617);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Studio G4', 618);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Memo Pad Smart 10', 619);
insert into cart (cartItemId, productId, quantity) values ('i-mate', 'i-mate JAM Black', 620);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia E72', 621);
insert into cart (cartItemId, productId, quantity) values ('BQ', 'BQ Aquaris U Plus', 622);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem my101X', 623);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel U5 HD', 624);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor Holly 2 Plus', 625);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N930', 626);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic T31', 627);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Blade Qlux 4G', 628);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C605', 629);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus 2 AS680', 630);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 1650', 631);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Bharat 2+', 632);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei MediaPad T3 8.0', 633);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips 399', 634);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Zylo', 635);
insert into cart (cartItemId, productId, quantity) values ('i-mobile', 'i-mobile TV658 Touch&Move', 636);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Blade C V807', 637);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview V1 Viper i4G', 638);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax A28 Bolt', 639);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Pixi 7', 640);
insert into cart (cartItemId, productId, quantity) values ('Mitsubishi', 'Mitsubishi M330', 641);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG V20', 642);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei nova 7 5G', 643);
insert into cart (cartItemId, productId, quantity) values ('Qtek', 'Qtek 8010', 644);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola M3688', 645);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn A3', 646);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Mi 6 Plus', 647);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens CX65', 648);
insert into cart (cartItemId, productId, quantity) values ('Apple', 'Apple Watch Edition Series 2 42mm', 649);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava A76', 650);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Andy C5E LTE', 651);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-C552', 652);
insert into cart (cartItemId, productId, quantity) values ('Prestigio', 'Prestigio MultiPhone 5300 Duo', 653);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola SPICE Key XT317', 654);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Dual 5', 655);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Studio G Plus HD', 656);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview P10 Style', 657);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Note20 5G', 658);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola W209', 659);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy A41', 660);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile G3', 661);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Sol', 662);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Shine Lite', 663);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung i530', 664);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G Watch W100', 665);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Studio G LTE', 666);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A526', 667);
insert into cart (cartItemId, productId, quantity) values ('Posh', 'Posh Revel S500', 668);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee M2', 669);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-813D', 670);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola MOTOSMART MIX XT550', 671);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo Reno A', 672);
insert into cart (cartItemId, productId, quantity) values ('Icemobile', 'Icemobile Prime 5.0 Plus', 673);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6151', 674);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 2', 675);
insert into cart (cartItemId, productId, quantity) values ('VK', 'VK Mobile VK7000', 676);
insert into cart (cartItemId, productId, quantity) values ('BenQ', 'BenQ M775C', 677);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-E265', 678);
insert into cart (cartItemId, productId, quantity) values ('Mitsubishi', 'Mitsubishi Trium Aria', 679);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Y5p', 680);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung X120', 681);
insert into cart (cartItemId, productId, quantity) values ('Vertu', 'Vertu Signature Touch (2015)', 682);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Mate X2', 683);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE N910', 684);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC S630', 685);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei P10 Lite', 686);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens S35i', 687);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy A3 (2017)', 688);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG A140', 689);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei P30 lite', 690);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenwatch 3 WI503Q', 691);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips V526', 692);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Optimus 4X HD P880', 693);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool i674', 694);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab Pro 8.4', 695);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Elife E5', 696);
insert into cart (cartItemId, productId, quantity) values ('Energizer', 'Energizer Hardcase H241', 697);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GT405', 698);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M7600 Beat DJ', 699);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic T40', 700);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Redmi Note', 701);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem MY C2-3', 702);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola ZN5', 703);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6681', 704);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips X332', 705);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Xenium 9@9', 706);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola ROKR E6', 707);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6270', 708);
insert into cart (cartItemId, productId, quantity) values ('Palm', 'Palm Pre', 709);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C5050 Star', 710);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenfone 2 ZE500CL', 711);
insert into cart (cartItemId, productId, quantity) values ('Yota', 'Yota YotaPhone 2', 712);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG K41S', 713);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung T139', 714);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy C9 Pro', 715);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung R351 Freeform', 716);
insert into cart (cartItemId, productId, quantity) values ('T-Mobile', 'T-Mobile Vivacity', 717);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab 10.1 P7510', 718);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C207', 719);
insert into cart (cartItemId, productId, quantity) values ('i-mate', 'i-mate PDA2', 720);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KP235', 721);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 825', 722);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-306', 723);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire S', 724);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab 3 Lite 7.0', 725);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview Viva H8 LTE', 726);
insert into cart (cartItemId, productId, quantity) values ('i-mate', 'i-mate Ultimate 6150', 727);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Iconia Tab A200', 728);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KG320', 729);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Imperial II', 730);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y71i', 731);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 7.1', 732);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Deejay Flip', 733);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 7110', 734);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice S-7000', 735);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-385', 736);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenfone 2 Laser ZE550KL', 737);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile Noir Z9', 738);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia Watch', 739);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo X21 UD', 740);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 1100', 741);
insert into cart (cartItemId, productId, quantity) values ('Xiaomi', 'Xiaomi Mi 10 5G', 742);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenfone Live ZB501KL', 743);
insert into cart (cartItemId, productId, quantity) values ('Apple', 'Apple iPhone 4', 744);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Warp 4G', 745);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab A 8.0 (2017)', 746);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G4 Stylus', 747);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 7280', 748);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola VE75', 749);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Liquid Z200', 750);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile Noir Z5', 751);
insert into cart (cartItemId, productId, quantity) values ('Innostream', 'Innostream INNO 50', 752);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Metro TV', 753);
insert into cart (cartItemId, productId, quantity) values ('Sendo', 'Sendo S360', 754);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Strike', 755);
insert into cart (cartItemId, productId, quantity) values ('Intex', 'Intex Aqua Y2 Remote', 756);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6234', 757);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Y6 Pro (2019)', 758);
insert into cart (cartItemId, productId, quantity) values ('Apple', 'Apple Watch Sport 42mm (1st gen)', 759);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Link II', 760);
insert into cart (cartItemId, productId, quantity) values ('BQ', 'BQ Aquaris M5.5', 761);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Racer II', 762);
insert into cart (cartItemId, productId, quantity) values ('Telit', 'Telit GM 830', 763);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung U900 Soul', 764);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab 2 10.1 P5110', 765);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel 3v', 766);
insert into cart (cartItemId, productId, quantity) values ('Lava', 'Lava 3G 402+', 767);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips X116', 768);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile Noir A6', 769);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 1616', 770);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Vivo 5 Mini', 771);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Tweek', 772);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola W231', 773);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G3 S', 774);
insert into cart (cartItemId, productId, quantity) values ('Mitac', 'Mitac MIO Leap K1', 775);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT 565', 776);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire U', 777);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Transformer Prime TF201', 778);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei U8180 IDEOS X1', 779);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy M11', 780);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Gator 5', 781);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 1200', 782);
insert into cart (cartItemId, productId, quantity) values ('Maxon', 'Maxon MX-A30', 783);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Elife S5.1', 784);
insert into cart (cartItemId, productId, quantity) values ('Apple', 'Apple iPad 9.7 (2018)', 785);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola StarTAC Rainbow', 786);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola GLEAM+ WX308', 787);
insert into cart (cartItemId, productId, quantity) values ('Microsoft', 'Microsoft Kin One', 788);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo K6', 789);
insert into cart (cartItemId, productId, quantity) values ('Dell', 'Dell Streak 10 Pro', 790);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG L5100', 791);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Wing 5G', 792);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 6030', 793);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Spark 3 Q385', 794);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-228', 795);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y52s', 796);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola C257', 797);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice Mi-425 Stellar', 798);
insert into cart (cartItemId, productId, quantity) values ('Microsoft', 'Microsoft Kin TWOm', 799);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A518', 800);
insert into cart (cartItemId, productId, quantity) values ('Prestigio', 'Prestigio MultiPad 7.0 Prime Duo 3G', 801);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo Vibe K4 Note', 802);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A59', 803);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Asha 500', 804);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Tab 2 10.1 P5100', 805);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y20i', 806);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice Mi-423 Smart Flo Ivory 2', 807);
insert into cart (cartItemId, productId, quantity) values ('Microsoft', 'Microsoft Lumia 950 XL', 808);
insert into cart (cartItemId, productId, quantity) values ('Karbonn', 'Karbonn A6', 809);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview X4 Soul Infinity Z', 810);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Dash 5.0', 811);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Ascend Y210D', 812);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung ATIV SE', 813);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips W632', 814);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy S5 Sport', 815);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy A20e', 816);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Transformer Prime TF201', 817);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia T3', 818);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M7500 Emporio Armani', 819);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC DB6000', 820);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 5233', 821);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Moto E7', 822);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia N2', 823);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A3', 824);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem my411X', 825);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Turbo', 826);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Fire S', 827);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Era 1X', 828);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei T330', 829);
insert into cart (cartItemId, productId, quantity) values ('Prestigio', 'Prestigio MultiPad Note 8.0 3G', 830);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Pop 2 F', 831);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenpad 10 Z300M', 832);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia Tablet S 3G', 833);
insert into cart (cartItemId, productId, quantity) values ('Spice', 'Spice M-6688 Flo Magic', 834);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C414', 835);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile Noir i5', 836);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy J2', 837);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic Toughpad FZ-A1', 838);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Genie 2000', 839);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KS360', 840);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Memo Pad 7 ME176C', 841);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei MatePad 5G', 842);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A359', 843);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Tri Chip C333', 844);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Play 4G Q469', 845);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N22i', 846);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview P6 Lite', 847);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy S21', 848);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor U8860', 849);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Genie Sport', 850);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 700 dual sim', 851);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens C11', 852);
insert into cart (cartItemId, productId, quantity) values ('Mitsubishi', 'Mitsubishi Trium Mars', 853);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Genie Sport', 854);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE nubia Z7 Max', 855);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Axon Elite', 856);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Pixi 3 (5.5)', 857);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 9 PureView', 858);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy M10s', 859);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung E1210', 860);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo Phab2', 861);
insert into cart (cartItemId, productId, quantity) values ('Palm', 'Palm Treo Pro', 862);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia 9 PureView', 863);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Andy AZ4.5', 864);
insert into cart (cartItemId, productId, quantity) values ('Toshiba', 'Toshiba Excite 13 AT335', 865);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung C3330 Champ 2', 866);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Watch GT 2', 867);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung SGH-250', 868);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung I9230 Galaxy Golden', 869);
insert into cart (cartItemId, productId, quantity) values ('Tecno', 'Tecno Phantom 8', 870);
insert into cart (cartItemId, productId, quantity) values ('OnePlus', 'OnePlus X', 871);
insert into cart (cartItemId, productId, quantity) values ('Maxwest', 'Maxwest Astro 3.5', 872);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Z350', 873);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung I9230 Galaxy Golden', 874);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Stratosphere II I415', 875);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel OT-813F', 876);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Lumia 520', 877);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei Nexus 6P', 878);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Transformer Pad TF300TG', 879);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool s5200 Orion', 880);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens S55', 881);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Blade A610', 882);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Xplay3S', 883);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo K6 Enjoy', 884);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson Vivaz pro', 885);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone Smart 4 turbo', 886);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Funbook 3G P560', 887);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone Chat 655', 888);
insert into cart (cartItemId, productId, quantity) values ('Eten', 'Eten P700', 889);
insert into cart (cartItemId, productId, quantity) values ('Infinix', 'Infinix Note 6', 890);
insert into cart (cartItemId, productId, quantity) values ('Meizu', 'Meizu C9', 891);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Xenium 9@9w', 892);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier V730', 893);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung S3600', 894);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Iconia Tab A501', 895);
insert into cart (cartItemId, productId, quantity) values ('Gigabyte', 'Gigabyte GSmart Guru GX', 896);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola MOTO MT620', 897);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Infinity Pro', 898);
insert into cart (cartItemId, productId, quantity) values ('Innostream', 'Innostream INNO 50', 899);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Pixi 4 (5)', 900);
insert into cart (cartItemId, productId, quantity) values ('VK', 'VK Mobile VK2200', 901);
insert into cart (cartItemId, productId, quantity) values ('Vodafone', 'Vodafone Smart Tab 10', 902);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola C118', 903);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Evo 4G', 904);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo IdeaPad A1', 905);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Asha 311', 906);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire 626 (USA)', 907);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier K3', 908);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer neoTouch P300', 909);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung Galaxy Xcover 4', 910);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Bharat 5 Infinity', 911);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor 7', 912);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson W508', 913);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo R9s Plus', 914);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Grand X IN', 915);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips Xenium F511', 916);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon A10', 917);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A31', 918);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor 7X', 919);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool R25', 920);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Era 4G', 921);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee M7 Power', 922);
insert into cart (cartItemId, productId, quantity) values ('verykool', 'verykool SL5000 Quantum', 923);
insert into cart (cartItemId, productId, quantity) values ('HP', 'HP iPAQ Data Messenger', 924);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG GT365 Neon', 925);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG Zero', 926);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo Tab 4 10', 927);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG V50 ThinQ 5G', 928);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview Soul X7 Style', 929);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo X20 Plus UD', 930);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung R220', 931);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M350 Seek', 932);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Pioneer P4', 933);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic T45', 934);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia Lumia 620', 935);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Ctrl V6L', 936);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee P12', 937);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Moto E4 Plus', 938);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Xperia ZR', 939);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Iconia Tab 10 A3-A40', 940);
insert into cart (cartItemId, productId, quantity) values ('Gionee', 'Gionee Gpad G2', 941);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola Quench XT5 XT502', 942);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO 8X-1020', 943);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Kis III V790', 944);
insert into cart (cartItemId, productId, quantity) values ('Energizer', 'Energizer Hardcase H10', 945);
insert into cart (cartItemId, productId, quantity) values ('Yezz', 'Yezz Zenior YZ888', 946);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem MY X5-2', 947);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KU311', 948);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax A63 Canvas Fun', 949);
insert into cart (cartItemId, productId, quantity) values ('NEC', 'NEC N22i', 950);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo Y11', 951);
insert into cart (cartItemId, productId, quantity) values ('alcatel', 'alcatel Pop Up', 952);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax A300 Canvas Gold', 953);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G Flex2', 954);
insert into cart (cartItemId, productId, quantity) values ('Ulefone', 'Ulefone Note 8', 955);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE Blade Q', 956);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax X265', 957);
insert into cart (cartItemId, productId, quantity) values ('vivo', 'vivo V20 2021', 958);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson J120', 959);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson K550im', 960);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo A7x', 961);
insert into cart (cartItemId, productId, quantity) values ('Fujitsu', 'Fujitsu Siemens T810', 962);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola V235', 963);
insert into cart (cartItemId, productId, quantity) values ('Nokia', 'Nokia N800', 964);
insert into cart (cartItemId, productId, quantity) values ('Celkon', 'Celkon C350', 965);
insert into cart (cartItemId, productId, quantity) values ('Haier', 'Haier A600', 966);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola DEFY XT XT556', 967);
insert into cart (cartItemId, productId, quantity) values ('Sagem', 'Sagem MW 3042', 968);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG KT610', 969);
insert into cart (cartItemId, productId, quantity) values ('Sony', 'Sony Ericsson K618', 970);
insert into cart (cartItemId, productId, quantity) values ('ZTE', 'ZTE A261', 971);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei MediaPad T1 7.0 Plus', 972);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung I5700 Galaxy Spica', 973);
insert into cart (cartItemId, productId, quantity) values ('Panasonic', 'Panasonic G50', 974);
insert into cart (cartItemId, productId, quantity) values ('Motorola', 'Motorola VE538', 975);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG G4 Dual', 976);
insert into cart (cartItemId, productId, quantity) values ('BLU', 'BLU Neo X Plus', 977);
insert into cart (cartItemId, productId, quantity) values ('Honor', 'Honor Magic 2 3D', 978);
insert into cart (cartItemId, productId, quantity) values ('Huawei', 'Huawei P20 lite (2019)', 979);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax X352', 980);
insert into cart (cartItemId, productId, quantity) values ('Lenovo', 'Lenovo A7-30 A3300', 981);
insert into cart (cartItemId, productId, quantity) values ('LG', 'LG U400', 982);
insert into cart (cartItemId, productId, quantity) values ('Micromax', 'Micromax Canvas Hue', 983);
insert into cart (cartItemId, productId, quantity) values ('Oppo', 'Oppo Find 5 Mini', 984);
insert into cart (cartItemId, productId, quantity) values ('QMobile', 'QMobile J7 Pro', 985);
insert into cart (cartItemId, productId, quantity) values ('Allview', 'Allview P4 AllDro', 986);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Desire X', 987);
insert into cart (cartItemId, productId, quantity) values ('Philips', 'Philips V808', 988);
insert into cart (cartItemId, productId, quantity) values ('XOLO', 'XOLO Q1010', 989);
insert into cart (cartItemId, productId, quantity) values ('HTC', 'HTC Rhyme', 990);
insert into cart (cartItemId, productId, quantity) values ('Eten', 'Eten G500', 991);
insert into cart (cartItemId, productId, quantity) values ('Gigabyte', 'Gigabyte GSmart Classic', 992);
insert into cart (cartItemId, productId, quantity) values ('Siemens', 'Siemens A31', 993);
insert into cart (cartItemId, productId, quantity) values ('Plum', 'Plum Tag 2 3G', 994);
insert into cart (cartItemId, productId, quantity) values ('Asus', 'Asus Zenfone Go ZC451TG', 995);
insert into cart (cartItemId, productId, quantity) values ('Acer', 'Acer Liquid Jade 2', 996);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung A697 Sunburst', 997);
insert into cart (cartItemId, productId, quantity) values ('Samsung', 'Samsung M600', 998);
insert into cart (cartItemId, productId, quantity) values ('Sharp', 'Sharp 903', 999);
insert into cart (cartItemId, productId, quantity) values ('BenQ-Siemens', 'BenQ-Siemens CF61', 1000);
